import type { Metadata } from "next"
import Link from "next/link"
import { LegalPage, LegalSection } from "@/components/legal/legal-page"
import { siteConfig } from "@/lib/site-config"

export const metadata: Metadata = {
  title: "Privacy & Data Protection",
  description:
    "How Expat Health Clinic collects, uses, stores and protects your personal and medical data under the GDPR (AVG) and Dutch healthcare law.",
  alternates: { canonical: "/privacy" },
}

export default function PrivacyPage() {
  const { legal } = siteConfig

  return (
    <LegalPage
      title="Privacy & Data Protection Policy"
      intro="This policy explains how Expat Health Clinic processes personal data, including medical data, when you visit our website, contact us, or use our services. We process data in accordance with the General Data Protection Regulation (GDPR / AVG), the Dutch GDPR Implementation Act (UAVG), the Medical Treatment Contracts Act (WGBO) and other applicable Dutch healthcare legislation."
      lastUpdated={legal.lastUpdated}
    >
      <LegalSection id="controller" title="1. Who is responsible for your data">
        <p>
          The data controller is {legal.legalEntityName}, registered with the Dutch Chamber of Commerce (KvK) under
          number {legal.kvkNumber}, with its registered (correspondence) address at {legal.registeredAddress}. This
          address is not a clinic site.
        </p>
        <p>
          For any question about this policy or to exercise your rights, contact our data protection contact at{" "}
          <a href={`mailto:${legal.dataProtectionContact}`}>{legal.dataProtectionContact}</a> or{" "}
          <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>.
        </p>
      </LegalSection>

      <LegalSection id="data-we-collect" title="2. What data we collect">
        <p>Depending on how you interact with us, we may process the following categories of personal data:</p>
        <ul>
          <li>
            <strong>Identity and contact data</strong> – name, email address, telephone number, date of birth,
            nationality and preferred language.
          </li>
          <li>
            <strong>Appointment data</strong> – requested service, chosen location, appointment date and time, and
            booking references generated by our booking platform.
          </li>
          <li>
            <strong>Medical data (special category data)</strong> – health concerns you share with us, medical history,
            medication, examination results, referral letters, second-opinion documents and consultation notes.
          </li>
          <li>
            <strong>Insurance and billing data</strong> – insurer name, policy number, invoices and payment status. We do
            not store full card details; payments are processed by our booking and payment providers.
          </li>
          <li>
            <strong>Corporate / TPA data</strong> – company name, contact person and case references when we act on
            behalf of an employer, insurer or third-party administrator.
          </li>
          <li>
            <strong>Website usage data</strong> – IP address (anonymised for analytics), browser type, pages visited and
            interactions, only if you consent to analytics cookies.
          </li>
          <li>
            <strong>Website assistant conversations</strong> – text or audio you share with our automated assistant, only
            if you consent to loading it (see section 7).
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="purposes" title="3. Why we process your data and on what legal basis">
        <ul>
          <li>
            <strong>Providing medical care</strong> (consultations, screenings, second opinions, referrals) – Article
            9(2)(h) GDPR together with the treatment contract under the WGBO and Article 6(1)(b) GDPR.
          </li>
          <li>
            <strong>Maintaining a medical record</strong> – legal obligation under the WGBO (Article 6(1)(c) GDPR).
          </li>
          <li>
            <strong>Scheduling, invoicing and administration</strong> – performance of a contract (Article 6(1)(b)) and
            legal obligations under Dutch tax law (Article 6(1)(c)).
          </li>
          <li>
            <strong>Responding to enquiries</strong> submitted via our contact form, email or telephone – legitimate
            interest (Article 6(1)(f)) and, where health information is included, your explicit consent (Article 9(2)(a)).
          </li>
          <li>
            <strong>Corporate and TPA services</strong> – performance of the agreement with the organisation, and your
            explicit consent or the treatment relationship for any medical data.
          </li>
          <li>
            <strong>Website analytics and the automated assistant</strong> – your consent (Article 6(1)(a)), which you can
            withdraw at any time via the "Cookie preferences" link in the footer.
          </li>
          <li>
            <strong>Safety, security and legal claims</strong> – legitimate interest (Article 6(1)(f)).
          </li>
        </ul>
        <p>We never sell personal data and we do not use medical data for marketing.</p>
      </LegalSection>

      <LegalSection id="recipients" title="4. Who receives your data">
        <p>We share data only where necessary and with parties bound by confidentiality and data processing agreements:</p>
        <ul>
          <li>
            <strong>Our physicians and medical staff</strong>, who are bound by medical professional secrecy.
          </li>
          <li>
            <strong>Your regular GP (huisarts) or other healthcare providers</strong> – only with your explicit
            permission, for example when we send a referral or consultation summary.
          </li>
          <li>
            <strong>Booking and payment platform</strong> (Trafft) – for appointment scheduling and payments.
          </li>
          <li>
            <strong>Website hosting</strong> (Vercel Inc.) – for serving this website and, with consent, privacy-friendly
            visitor statistics.
          </li>
          <li>
            <strong>Google Ireland Ltd.</strong> (Google Analytics) – only with your consent; IP anonymisation is enabled.
          </li>
          <li>
            <strong>ElevenLabs Inc.</strong> – provider of our automated website assistant; only loaded with your
            consent.
          </li>
          <li>
            <strong>Email and document providers</strong> used for secure communication and record storage.
          </li>
          <li>
            <strong>Insurers, employers or TPAs</strong> – only the information you have authorised us to share, or where
            they are the contracting party for your care.
          </li>
          <li>
            <strong>Authorities</strong> – where required by law, for example the Dutch Health and Youth Care
            Inspectorate (IGJ) or tax authorities.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="transfers" title="5. International transfers">
        <p>
          Some providers (Vercel, Google, ElevenLabs) may process data outside the European Economic Area, mainly in the
          United States. Where this happens we rely on the EU–US Data Privacy Framework and/or the European
          Commission&apos;s Standard Contractual Clauses, together with additional safeguards. Medical records themselves
          are stored within the EEA.
        </p>
      </LegalSection>

      <LegalSection id="retention" title="6. How long we keep your data">
        <ul>
          <li>
            <strong>Medical records</strong> – at least 20 years after the last change to the record, as required by the
            WGBO, or longer where good medical practice requires it.
          </li>
          <li>
            <strong>Financial and invoicing records</strong> – 7 years, as required by Dutch tax law.
          </li>
          <li>
            <strong>Contact form and email enquiries</strong> that do not lead to a treatment relationship – up to 12
            months.
          </li>
          <li>
            <strong>Analytics data</strong> – up to 14 months (Google Analytics default) in aggregated form.
          </li>
          <li>
            <strong>Assistant conversations</strong> – retained by ElevenLabs according to their retention settings and
            our processing agreement; we do not add them to your medical record unless you ask us to.
          </li>
          <li>
            <strong>Cookie consent choice</strong> – 6 months.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="cookies" title="7. Cookies, analytics and the website assistant">
        <p>
          When you first visit, only strictly necessary cookies are set. Optional tools are loaded only after you click
          &quot;Accept all&quot; in the cookie banner. You can change your choice at any time via the &quot;Cookie
          preferences&quot; link in the footer.
        </p>
        <ul>
          <li>
            <strong>Essential</strong> – <code>ehc_cookie_consent</code> stores your cookie choice (6 months).
          </li>
          <li>
            <strong>Analytics (optional)</strong> – Google Analytics (<code>_ga</code>, <code>_ga_*</code>, up to 14
            months) and Vercel Analytics (cookieless, aggregated) help us understand how the website is used.
          </li>
          <li>
            <strong>Website assistant (optional)</strong> – the {siteConfig.aiAssistant.name} is an automated
            conversational tool provided by ElevenLabs. It answers general questions about our services. It is{" "}
            <strong>not a doctor</strong>, does not provide medical advice or diagnosis, and must not be used in an
            emergency (call 112). Please avoid sharing detailed medical information with it; use the contact form or book
            an appointment instead.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="security" title="8. How we protect your data">
        <p>
          We apply appropriate technical and organisational measures, including encrypted connections (TLS), access
          controls limited to staff who need the data, confidentiality obligations for all staff, data processing
          agreements with suppliers, and regular review of our systems. Medical information is handled in line with the
          NEN 7510 information security principles for Dutch healthcare.
        </p>
        <p>
          Email is not fully secure. If you prefer, you can share sensitive documents during your appointment or ask us
          for a secure upload option.
        </p>
      </LegalSection>

      <LegalSection id="rights" title="9. Your rights">
        <p>Under the GDPR and the WGBO you have the right to:</p>
        <ul>
          <li>access your personal data and receive a copy of your medical record;</li>
          <li>have inaccurate data rectified or supplemented;</li>
          <li>request erasure, subject to our statutory retention duties for medical records;</li>
          <li>restrict or object to processing based on legitimate interest;</li>
          <li>receive your data in a portable format;</li>
          <li>withdraw consent at any time, without affecting processing that took place before withdrawal;</li>
          <li>
            lodge a complaint with the Dutch Data Protection Authority (Autoriteit Persoonsgegevens,{" "}
            <a href="https://www.autoriteitpersoonsgegevens.nl" target="_blank" rel="noopener noreferrer">
              autoriteitpersoonsgegevens.nl
            </a>
            ).
          </li>
        </ul>
        <p>
          To exercise a right, email <a href={`mailto:${legal.dataProtectionContact}`}>{legal.dataProtectionContact}</a>
          . We respond within one month and may ask you to verify your identity before releasing medical information.
        </p>
      </LegalSection>

      <LegalSection id="children" title="10. Children">
        <p>
          We treat children and families. For patients under 16, we process data with the consent of a parent or legal
          guardian in line with the WGBO, and we involve children aged 12 to 15 in decisions about their own care as
          the law requires.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="11. Changes to this policy">
        <p>
          We may update this policy when our services or the law change. The date at the top shows the latest version.
          Material changes will be highlighted on this page.
        </p>
        <p>
          See also our <Link href="/terms">Terms & Conditions</Link>, including our{" "}
          <Link href="/terms#complaints">complaints procedure</Link>.
        </p>
      </LegalSection>
    </LegalPage>
  )
}
